# IEOR 290 003 Data X
## HOMEWORK 2
### Name: Yujia Xu
### SID: 3032144766

In [32]:
import numpy as np

In [4]:
# Create two numpy arrays (a and b). 
# a should be all integers between 10-19 (inclusive), and b should be ten evenly spaced numbers between 1-7.
a = np.arange(10,20)
b = np.linspace(1,7,10)

In [5]:
# Square all the elements in both arrays (element-wise)
print a**2,b**2

[100 121 144 169 196 225 256 289 324 361] [  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]


In [8]:
# Add both the squared arrays
c = a**2 + b**2
print c

[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]


In [10]:
# Sum the even elements of the added array
sum_even = 0
for i in range(len(c)):
    if i % 2 == 1:
        sum_even += c[i]
print sum_even

1276.66666667


In [11]:
# Take the square root of the added array (element-wise square root)
print np.sqrt(c)

[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


In [17]:
# Append b to a, reshape the appended array so that it is a 5x4, 
# 2d array and store the results in a variable called m. Print m.
c = np.hstack((a,b))
m = c.reshape(5,4)
print m

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


In [19]:
# Extract the second and the third column of the m matrix. 
# Store the resulting 5x2 matrix in a new variable called m2. Print m2.
m2 = m[:,1:3]
print m2

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


In [21]:
# Take the dot product of m2T and m store 
# the results in a matrix called m3. Print m3.
m3 = np.dot(m2.T,m)
print m3

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


In [22]:
# Round the m3 matrix to two decimal points. Store the result in place and print the new m3
m3 = np.around(m3,2)
print m3

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


In [27]:
s = np.sort(m3)
print s

[[ 437.89  482.33  697.33  748.11]
 [ 402.22  437.89  454.56  489.89]]


In [41]:
# Sort the m3 array so that the highest value is at the top left, the next highest value to the right of the highest, 
# and the lowest value is at the bottom right. Print the sorted m3 array.
s = m3.reshape(1,8)
s1 = np.sort(s,axis=None)
s2 = s1[::-1]
m3 = s2.reshape(2,4)
print m3

[[ 748.11  697.33  489.89  482.33]
 [ 454.56  437.89  437.89  402.22]]
